import React, { useState, useEffect } from 'react';
import { useTheme } from '../../contexts/ThemeContext';
import { api } from '../../services/api';
import { Globe2, Search, FileText, Settings2, Sparkles, Check, Loader2 } from 'lucide-react';
import axios from 'axios';

export default function OmniSiteConfig() {
  const { theme } = useTheme();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [settings, setSettings] = useState(null);
  const [branding, setBranding] = useState({
    custom_domain: 'luminasalon.com',
    robots_txt: '',
    llms_txt: ''
  });

  useEffect(() => {
    fetchSettings();
  }, []);

  const fetchSettings = async () => {
    try {
      const res = await api.getCompanySettings();
      setSettings(res.data);
      if (res.data?.general_settings?.branding) {
        setBranding({ ...branding, ...res.data.general_settings.branding });
      }
    } catch (error) {
      console.error('Failed to fetch settings:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (e) => {
    if(e) e.preventDefault();
    setSaving(true);
    try {
      const updatedSettings = {
        ...settings,
        general_settings: {
          ...settings?.general_settings,
          branding: branding
        }
      };
      await api.updateCompanySettings(updatedSettings);
      alert('Site Configuration saved successfully!');
    } catch (err) {
      alert('Failed to save settings.');
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateAEO = async () => {
    setGenerating(true);
    try {
      // We call the backend Python endpoint which we will build in Phase 3
      const token = localStorage.getItem('ridn_token');
      const res = await axios.post(`${process.env.REACT_APP_API_URL || 'http://localhost:8000/api'}/omni/generate-aeo`, {}, {
         headers: { Authorization: `Bearer ${token}` }
      });
      if(res.data) {
         setBranding(prev => ({
            ...prev,
            robots_txt: res.data.robots_txt,
            llms_txt: res.data.llms_txt
         }));
         alert("AEO settings fully generated by AI!");
      }
    } catch (error) {
      console.error(error);
      alert('Failed to generate AEO content across API. Make sure Phase 3 is implemented.');
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return <div className="p-8">Loading configuration...</div>;

  return (
    <div className={`max-w-4xl mx-auto p-4 md:p-8 animate-in fade-in duration-500`}>
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className={`text-3xl font-bold flex items-center gap-3 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
            <Settings2 className="w-8 h-8 text-blue-500" /> Site Configuration
          </h1>
          <p className="text-gray-500 mt-2">Manage AEO mapping, custom domains, and AI-bot traversal contexts.</p>
        </div>
        <button 
          onClick={handleSave}
          disabled={saving || generating}
          className="flex items-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white px-6 py-3 rounded-xl font-bold shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all text-sm disabled:opacity-50"
        >
          {saving ? 'Saving Config...' : <><Check className="w-5 h-5" /> Save Configuration</>}
        </button>
      </div>

      <div className="space-y-8">
        {/* Domain Mapping */}
        <div className={`p-8 rounded-[2rem] shadow-sm border flex flex-col md:flex-row items-start md:items-center justify-between gap-6 ${theme === 'dark' ? 'bg-[#171C22] border-[#1F2630]' : 'bg-white border-gray-100'}`}>
           <div className="flex-1">
              <h2 className={`text-xl font-bold flex items-center gap-3 mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
                <Globe2 className="w-6 h-6 text-green-500" /> Custom Domain
              </h2>
              <p className="text-sm font-medium text-gray-500">Route your front-end white label to a custom URL.</p>
           </div>
           <div className="w-full md:w-auto">
              <input 
                 type="text" 
                 value={branding.custom_domain || ''} 
                 onChange={e => setBranding({...branding, custom_domain: e.target.value})}
                 placeholder="e.g. lumina.com"
                 className={`w-full md:w-72 rounded-xl border px-5 h-14 outline-none focus:ring-2 focus:ring-green-500 font-mono font-bold text-sm bg-transparent ${theme === 'dark' ? 'border-[#1F2630] text-green-400' : 'border-gray-200 text-green-700'}`}
              />
           </div>
        </div>

        {/* Answer Engine AI Automation */}
        <div className={`p-6 md:p-8 rounded-[2rem] shadow-lg border relative overflow-hidden ${theme === 'dark' ? 'bg-indigo-950/20 border-indigo-900/50' : 'bg-indigo-50 border-indigo-100'}`}>
           <div className="absolute -right-10 -top-10 text-[10rem] opacity-5 pointer-events-none">✨</div>
           <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8 relative z-10 mb-10">
              <div className="flex-1">
                 <div className="inline-flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold tracking-widest uppercase text-xs mb-4 bg-indigo-100 dark:bg-indigo-900/30 px-3 py-1.5 rounded-full shadow-sm">
                    <Sparkles className="w-4 h-4" /> Omni Intelligence
                 </div>
                 <h2 className={`text-3xl font-black tracking-tight mb-3 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>Generate AEO Metadata</h2>
                 <p className="text-gray-600 dark:text-gray-300 text-sm md:text-base font-medium max-w-lg leading-relaxed">
                    Click here to trigger our AI Engine to deeply scan your database, services, and brand settings. It will autonomously author highly-optimized `llms.txt` and `robots.txt` files to maximize organic indexing by Perplexity, SearchGPT, and other AI agents.
                 </p>
              </div>
              <button 
                onClick={handleGenerateAEO}
                disabled={generating}
                className="shrink-0 flex items-center justify-center gap-3 bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-5 rounded-2xl font-black shadow-xl hover:-translate-y-1 transition-transform disabled:opacity-50 disabled:hover:translate-y-0"
              >
                 {generating ? <Loader2 className="w-6 h-6 animate-spin" /> : <Sparkles className="w-6 h-6" />}
                 {generating ? 'AI Generating Context...' : 'Auto-Generate Schema'}
              </button>
           </div>

           <div className="grid grid-cols-1 md:grid-cols-2 gap-8 relative z-10">
              <div className="space-y-3">
                 <label className="text-sm font-bold text-gray-700 dark:text-gray-300 flex items-center gap-2"><Search className="w-4 h-4"/> robots.txt Override</label>
                 <textarea 
                   rows={8}
                   value={branding.robots_txt || ''}
                   onChange={e => setBranding({...branding, robots_txt: e.target.value})}
                   placeholder="AI will generate crawler logic here..."
                   className={`w-full rounded-2xl border p-5 outline-none font-mono text-xs leading-relaxed focus:ring-2 focus:ring-indigo-500 resize-none shadow-inner ${theme === 'dark' ? 'bg-[#0B0D10]/80 border-[#1F2630] text-gray-300' : 'bg-white/80 border-indigo-200 text-gray-700'}`}
                 />
              </div>
              <div className="space-y-3">
                 <label className="text-sm font-bold text-gray-700 dark:text-gray-300 flex items-center gap-2"><FileText className="w-4 h-4"/> llms.txt (LLM Agent Context)</label>
                 <textarea 
                   rows={8}
                   value={branding.llms_txt || ''}
                   onChange={e => setBranding({...branding, llms_txt: e.target.value})}
                   placeholder="AI will generate brand context for ChatGPT/Perplexity..."
                   className={`w-full rounded-2xl border p-5 outline-none font-mono text-xs leading-relaxed focus:ring-2 focus:ring-indigo-500 resize-none shadow-inner ${theme === 'dark' ? 'bg-[#0B0D10]/80 border-[#1F2630] text-gray-300' : 'bg-white/80 border-indigo-200 text-gray-700'}`}
                 />
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
