"""add_product_fields

Revision ID: 584925d62305
Revises: 4248b31bc807
Create Date: 2026-03-02 09:19:56.446630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584925d62305'
down_revision: Union[str, Sequence[str], None] = '4248b31bc807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_addon', sa.Boolean(), nullable=True))
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_addon')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
