"""Add lat and lng to Outlet

Revision ID: 69b997987063
Revises: a7876a89e9b3
Create Date: 2026-03-14 08:15:10.737950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b997987063'
down_revision: Union[str, Sequence[str], None] = 'a7876a89e9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlets', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('outlets', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outlets', 'longitude')
    op.drop_column('outlets', 'latitude')
    # ### end Alembic commands ###
