"""Add new feedback fields

Revision ID: a7876a89e9b3
Revises: 5b19c6c76f9b
Create Date: 2026-03-10 03:09:46.835471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7876a89e9b3'
down_revision: Union[str, Sequence[str], None] = '5b19c6c76f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('compared_to_previous', sa.String(length=50), nullable=True))
    op.add_column('feedback', sa.Column('liked_most', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('feedback', sa.Column('staff_shoutout', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('areas_fell_short', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('feedback', sa.Column('shortcomings_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('feedback', sa.Column('escalation_notes', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('escalation_contact_opt_in', sa.Boolean(), nullable=True))
    op.add_column('feedback', sa.Column('escalation_contact_number', sa.String(length=50), nullable=True))
    op.add_column('feedback', sa.Column('escalation_contact_time', sa.String(length=100), nullable=True))
    op.add_column('feedback', sa.Column('likely_to_visit_again', sa.String(length=50), nullable=True))
    op.add_column('feedback', sa.Column('nps_score', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('return_incentive', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('suggestions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'suggestions')
    op.drop_column('feedback', 'return_incentive')
    op.drop_column('feedback', 'nps_score')
    op.drop_column('feedback', 'likely_to_visit_again')
    op.drop_column('feedback', 'escalation_contact_time')
    op.drop_column('feedback', 'escalation_contact_number')
    op.drop_column('feedback', 'escalation_contact_opt_in')
    op.drop_column('feedback', 'escalation_notes')
    op.drop_column('feedback', 'shortcomings_details')
    op.drop_column('feedback', 'areas_fell_short')
    op.drop_column('feedback', 'staff_shoutout')
    op.drop_column('feedback', 'liked_most')
    op.drop_column('feedback', 'compared_to_previous')
    # ### end Alembic commands ###
