"""Change customer last_visit to Date

Revision ID: affc03a82275
Revises: e57fb700f193
Create Date: 2026-03-02 09:47:23.416869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affc03a82275'
down_revision: Union[str, Sequence[str], None] = 'e57fb700f193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'last_visit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="last_visit::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'last_visit',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
