"""add_whatsapp_config_and_message_log

Revision ID: c04b75cefba3
Revises: 5a9ba7bc90fb
Create Date: 2026-03-29 01:26:23.995590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c04b75cefba3'
down_revision: Union[str, Sequence[str], None] = '5a9ba7bc90fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('waba_id', sa.String(length=255), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('display_phone', sa.String(length=50), nullable=True),
    sa.Column('templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('whatsapp_message_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('wa_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_message_logs')
    op.drop_table('whatsapp_configs')
    # ### end Alembic commands ###
