"""update_company_model_for_superadmin

Revision ID: e57fb700f193
Revises: aed2ca9ea39b
Create Date: 2026-03-02 09:23:17.269514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e57fb700f193'
down_revision: Union[str, Sequence[str], None] = 'aed2ca9ea39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('plan_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('enabled_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('is_booking_enabled', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('is_retail_enabled', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('is_workplace_enabled', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('scheduled_deletion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('deactivation_reason', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_column('companies', 'created_by')
    op.drop_column('companies', 'deactivation_reason')
    op.drop_column('companies', 'scheduled_deletion_date')
    op.drop_column('companies', 'deactivated_at')
    op.drop_column('companies', 'is_workplace_enabled')
    op.drop_column('companies', 'is_retail_enabled')
    op.drop_column('companies', 'is_booking_enabled')
    op.drop_column('companies', 'enabled_features')
    op.drop_column('companies', 'trial_end')
    op.drop_column('companies', 'trial_start')
    op.drop_column('companies', 'plan_limits')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'business_type')
    # ### end Alembic commands ###
