"""add_razorpay_config

Revision ID: f6828b89831a
Revises: c04b75cefba3
Create Date: 2026-03-31 04:02:05.744432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6828b89831a'
down_revision: Union[str, Sequence[str], None] = 'c04b75cefba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('linked_account_name', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=255), nullable=True),
    sa.Column('bank_account_type', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('razorpay_account_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_stakeholder_id', sa.String(length=100), nullable=True),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('penny_test_status', sa.String(length=50), nullable=True),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('razorpay_configs')
    # ### end Alembic commands ###
